name: CDK Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
  
      - name: Run CDK Build and Test
        run: | 
          npm install
          npm run build
      - name: Run test coverage
        run: |
          npm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
